name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache: true

      - name: Go fmt
        run: |
          test -z "$(gofmt -l .)" || (echo "Please run gofmt" && gofmt -w . && exit 1)

      - name: Go vet
        run: go vet ./...

      - name: Go test
        run: go test ./... -count=1
